package com.example.Crackers.Services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import com.example.Crackers.Repositories.UserProfilesRespository;
import org.springframework.mail.javamail.JavaMailSender;
import jakarta.mail.internet.MimeMessage;

@Service
public class EmailSenderService {
	
	@Autowired
	private JavaMailSender emailSender;
	
	@Autowired
	private UserProfilesRespository userProfilesRespository;
	
	private String fromEmail = "testtoto2022@gmail.com";
	
	/**
	 * It sends a confirmation mail to the user with a 6 digit OTP
	 * 
	 * @param userId The user's id.
	 * @param toEmail The email address of the user to whom the email is to be sent.
	 * @param confirmationToken This is the 6 digit OTP that is generated by the system and sent to the user's email address.
	 */
	public void confirmationMailSender(int userId, String toEmail, String confirmationToken) {
		try {
			MimeMessage mimeMessage = emailSender.createMimeMessage();
			MimeMessageHelper mimeHelper = new MimeMessageHelper(mimeMessage, "utf-8");
			
			String nickName = userProfilesRespository.findById(userId).get().getFirstName();
			String msgBody = "<h3>Hi, " + nickName + "</h3>"
					+ "<p>Congratulations on making your first step with NeuBorn Crackers. Your account is created successfully.</p>"
					+ "<p>Please enter the below 6 digit OTP in the account confirmation screen to activate & verify your account.</p>"
					+ "<h3>Account verification OTP: </h3><h3 style='color: red;'>" + confirmationToken + "</h3>"
					+ "<p>Thank you</p>";
			
			mimeHelper.setText(msgBody, true);
			mimeHelper.setTo(toEmail);
			mimeHelper.setSubject("Account Verification OTP - TOT");
			mimeHelper.setFrom(fromEmail);
			
			emailSender.send(mimeMessage);
		} catch (Exception e) {
			throw new RuntimeException("Failed to send confirmation mail to the user:\t" + e.getMessage());
		}
	}
	
	/**
	 * It sends an email to the user with a confirmation token
	 * 
	 * @param userId The user's id
	 * @param toEmail The email address of the user who has requested for the password change.
	 * @param confirmationToken This is the OTP that is generated by the system and sent to the user's email address.
	 */
	public void forgotPasswordMailSender(int userId, String toEmail, String confirmationToken) {
		try {
			MimeMessage mimeMessage = emailSender.createMimeMessage();
			MimeMessageHelper mimeHelper = new MimeMessageHelper(mimeMessage, "utf-8");
			
			String nickName = userProfilesRespository.findById(userId).get().getFirstName();
			String msgBody = "<h3>Hi, " + nickName + "</h3>"
					+ "<p>Request for password change has been initiated from your account.</p>"
					+ "<p>Kindly go to the below</p>"
					+ "<h3>Account verification OTP: </h3><h3 style='color: red;'>" + confirmationToken + "</h3>"
					+ "<p>Thank you</p>";
			
			mimeHelper.setText(msgBody, true);
			mimeHelper.setTo(toEmail);
			mimeHelper.setSubject("Forgot Password OTP - TOT");
			mimeHelper.setFrom(fromEmail);
			
			emailSender.send(mimeMessage);
		} catch (Exception e) {
			throw new RuntimeException("Failed to send forgot password mail to the user:\t" + e.getMessage());
		}
	}
	
	/**
	 * It sends a mail to the admin user with a link to change password
	 * 
	 * @param userId The user's id
	 * @param toEmail The email address of the user who has requested for password change.
	 * @param confirmationToken This is the token that is generated by the system and is sent to the
	 * user's email address.
	 */
	public void adminForgotPasswordMailSender(int userId, String toEmail, String confirmationToken) {
		try {
			MimeMessage mimeMessage = emailSender.createMimeMessage();
			MimeMessageHelper mimeHelper = new MimeMessageHelper(mimeMessage, "utf-8");
			
			String baseURL = "123.136.195.69:3306/tot";
			String URL = "http://"+ baseURL +"/admin/change-password?id=" + userId + "&key=" + confirmationToken;
			String nickName = userProfilesRespository.findById(userId).get().getFirstName();
			String msgBody = "<h3>Hi, " + nickName + "</h3>"
					+ "<p>Request for password change has been initiated from our account.</p>"
					+ "<p>Kindly go to the below URL to change password:</p>"
					+ "<div style=\"text-align: center;\">"
					+ "<a href=\"" + URL + "\">"
					+ "    <button type=\"button\" style=\"background-color: #5797e2; border: none; border-radius: 1em; color: #fff; padding: 1em; font-weight: bold;\">Click here</button>"
					+ "</a>"
					+ "<h4>or copy the below link and paste in URL bar</h4>"
					+ "<p>" + URL + "</p>"
					+ "</div>"
					+ "<p>Thank you</p>";
			
			mimeHelper.setText(msgBody, true);
			mimeHelper.setTo(toEmail);
			mimeHelper.setSubject("Forgot Password - ADMIN - TOT");
			mimeHelper.setFrom(fromEmail);
			
			emailSender.send(mimeMessage);
		} catch (Exception e) {
			throw new RuntimeException("Failed to send forgot password mail to the user:\t" + e.getMessage());
		}
	}
	
	/**
	 * It sends an email to the admin user with the new password
	 * 
	 * @param userId The user's id
	 * @param toEmail The email address of the user
	 * @param password The new password generated by the system.
	 */
	public void resetPasswordMailSender(int userId, String toEmail, String password) {
		try {
			MimeMessage mimeMessage = emailSender.createMimeMessage();
			MimeMessageHelper mimeHelper = new MimeMessageHelper(mimeMessage, "utf-8");
			
			String nickName = userProfilesRespository.findById(userId).get().getFirstName();
			String msgBody = "<h3>Hi, " + nickName + "</h3>"
					+ "<p>Your account password has been reset by administrator.</p>"
					+ "<h3>New Password: </h3><h3 style='color: red;'>" + password + "</h3>"
					+ "<p>If you have not requested for the password reset, kindly contact our administrator through <a href='mailto:info@nippon-academy.ac.jp'>info@nippon-academy.ac.jp</a>.</p>"
					+ "<p style='color: red;'><strong>NOTE:</strong> This is confidential and do not share this with others for your own account security.</p>"
					+ "<p>Thank you</p>";
			
			mimeHelper.setText(msgBody, true);
			mimeHelper.setTo(toEmail);
			mimeHelper.setSubject("Reset Password - TOT");
			mimeHelper.setFrom(fromEmail);
			
			emailSender.send(mimeMessage);
		} catch (Exception e) {
			throw new RuntimeException("Failed to send password reset by admin mail to the user:\t" + e.getMessage());
		}
	}
	
	/**
	 * It sends an email to the user with a confirmation token to delete his/her account
	 * 
	 * @param userId The user's id
	 * @param toEmail The email address of the user who is requesting to delete his/her account.
	 * @param confirmationToken This is the OTP that will be sent to the user's email address.
	 */
	public void deleteRequestMailSender(int userId, String toEmail, String confirmationToken) {
		try {
			MimeMessage mimeMessage = emailSender.createMimeMessage();
			MimeMessageHelper mimeHelper = new MimeMessageHelper(mimeMessage, "utf-8");
			String nickName = userProfilesRespository.findById(userId).get().getFirstName();
			String msgBody = "<h3>Hi, " + nickName + "</h3>"
					+ "<p>We are sorry to hear you go. Note that if you delete your account, you will not be able to retrieve your data.</p>"
					+ "<h3>Account verification OTP: </h3><h3 style='color: red;'>" + confirmationToken + "</h3>"
					+ "<p>Thank you</p>";
			
			mimeHelper.setText(msgBody, true);
			mimeHelper.setTo(toEmail);
			mimeHelper.setSubject("Account Deletion OTP - TOT");
			mimeHelper.setFrom(fromEmail);
			
			emailSender.send(mimeMessage);
		} catch (Exception e) {
			throw new RuntimeException("Failed to send forgot password mail to the user:\t" + e.getMessage());
		}
	}

}
