spring.application.name=Crackers
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/crackers_db
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
server.port=8080

# Development Email SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testtoto2022@gmail.com
spring.mail.password=whhbhhimtkwdlsdo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
